name: HACS and hassfest validation

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "17 3 * * 1"
  workflow_dispatch:

permissions: {}

jobs:
  hacs:
    name: HACS
    runs-on: ubuntu-latest
    steps:
      - name: Run HACS validation
        uses: hacs/action@1ebf01c408f29afcb6406bd431bc98fd8cbb15aa # main
        with:
          category: integration

  hassfest:
    name: Hassfest
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@f4ca6f671bd429efb108c0f2fa0ae8af0215986c # master
